spring:
  application:
    name: timesheetApi
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MySQL_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

tms:
  app:
    SecretKey: ${SECRET_KEY}
